<!DOCTYPE html>
<html lang="pt-br">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Just Do Eat - Pedidos</title><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/dashboardv2.css"></head>
<body>
    <header class="header-dashboard"><div class="container"><a href="index.html"><img src="/images/icons/logo_justdoeat.png" alt="Logo Just Do Eat" class="logo-pequena"></a><nav><ul><li><a href="dashboardv2.html">Dashboard</a></li><li><a href="listar.html">Cardapio</a></li><li><a href="relatorios-restaurante.html">Relatorios</a></li></ul></nav><div class="header-actions"><form action="/api/logout" method="post"><button type="submit" class="btn btn-secondary">Sair</button></form></div></div></header>
    <div class="page-background-wrapper"><div class="page-logo-center"><img src="/images/icons/logo_justdoeat.png" alt="Logo Just Do Eat"><h1>Pedidos Recebidos</h1></div><main class="container"><div class="dashboard-container"><aside class="sidebar"><h2>Dashboard</h2><ul class="sidebar-menu"><li><a href="dashboardv2.html">Visao geral</a></li><li><a href="pedidos-restaurante.html" class="active">Pedidos</a></li><li><a href="listar.html">Cardapio</a></li><li><a href="relatorios-restaurante.html">Relatorios</a></li><li><a href="config-restaurante.html">Configuracao</a></li></ul></aside><section class="main-content"><h2>Fila de preparo</h2><div class="dashboard-list"><article class="dashboard-row" data-order-row><h3>Pedido #1024</h3><p>2x Combo Whopper, 1x Refrigerante</p><p>Status: <strong data-status-text>Pendente</strong></p><div class="dashboard-actions-inline"><button class="btn btn-secondary" data-order-status="Preparando">Preparando</button><button class="btn btn-primary" data-order-status="Saiu para Entrega">Saiu para Entrega</button></div></article><article class="dashboard-row" data-order-row><h3>Pedido #1025</h3><p>1x Ribs, 1x Cha Gelado</p><p>Status: <strong data-status-text>Preparando</strong></p><div class="dashboard-actions-inline"><button class="btn btn-secondary" data-order-status="Preparando">Preparando</button><button class="btn btn-primary" data-order-status="Saiu para Entrega">Saiu para Entrega</button></div></article></div></section></div></main></div>
    <script src="/js/app.js"></script><script src="/js/dashboard-actions.js"></script>
</body>
</html>

